# Generated by Django 6.0.7 on 2026-07-25 19:06

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Başlık / Emsal No')),
                ('doc_type', models.CharField(choices=[('KANUN', 'Mevzuat / Kanun'), ('YARGITAY', 'Yargıtay Kararı'), ('AYM', 'Anayasa Mahkemesi Kararı')], default='YARGITAY', max_length=20)),
                ('source_url', models.URLField(unique=True, verbose_name='Kaynak Adresi')),
                ('raw_content', models.TextField(verbose_name='Ham Metin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField(help_text='Parçanın metin içindeki sırası')),
                ('content', models.TextField(verbose_name='Parça Metni')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.legaldocument')),
            ],
        ),
    ]
